"""Domain models and evidence retrieval for Xingxi."""

from .authorization import evaluate_source_access
from .models import (
    AuthorizationStatus,
    AuthorizedUse,
    Citation,
    CopyrightStatus,
    Entity,
    EntityAlias,
    EntityType,
    Evidence,
    EvidenceRecord,
    HistoricalRelation,
    ReviewStatus,
    SearchFilters,
    SearchHit,
    SearchRequest,
    SearchResponse,
    SearchStatus,
    SourceAccessDecision,
    SourceAuthorizationEvent,
    SourceDocument,
    SourceDocumentStatus,
    SourceFile,
    SourceLevel,
    SourceType,
    TextChunk,
    VisibilityScope,
)
from .parsing import DocumentParseError, DocumentParseRequest, ParsedBlock, ParsedDocument, ParsedDocumentContent, parse_document
from .repositories import (
    AsyncEvidenceRepository,
    DuplicateSourceFileError,
    EvidenceRepository,
    InMemoryEvidenceRepository,
    InMemoryParsedDocumentRepository,
    InMemorySourceDocumentRepository,
    InMemorySourceFileRepository,
    ParsedDocumentRepository,
    SourceDocumentLibraryFile,
    SourceDocumentLibraryItem,
    SourceDocumentLibraryRepository,
    SourceDocumentRepository,
    SourceFileRepository,
)
from .retrieval import AsyncEvidenceSearchService, EvidenceSearchService

__all__ = [
    "AuthorizationStatus",
    "AuthorizedUse",
    "Citation",
    "CopyrightStatus",
    "DuplicateSourceFileError",
    "Entity",
    "EntityAlias",
    "EntityType",
    "Evidence",
    "EvidenceRecord",
    "AsyncEvidenceRepository",
    "AsyncEvidenceSearchService",
    "EvidenceRepository",
    "EvidenceSearchService",
    "DocumentParseError",
    "DocumentParseRequest",
    "HistoricalRelation",
    "InMemoryEvidenceRepository",
    "InMemoryParsedDocumentRepository",
    "ParsedBlock",
    "ParsedDocument",
    "ParsedDocumentContent",
    "ParsedDocumentRepository",
    "ReviewStatus",
    "SearchFilters",
    "SearchHit",
    "SearchRequest",
    "SearchResponse",
    "SearchStatus",
    "SourceDocument",
    "SourceDocumentRepository",
    "SourceDocumentLibraryFile",
    "SourceDocumentLibraryItem",
    "SourceDocumentLibraryRepository",
    "SourceDocumentStatus",
    "SourceFile",
    "SourceFileRepository",
    "SourceAccessDecision",
    "SourceAuthorizationEvent",
    "SourceLevel",
    "SourceType",
    "TextChunk",
    "VisibilityScope",
    "evaluate_source_access",
    "InMemorySourceDocumentRepository",
    "InMemorySourceFileRepository",
    "parse_document",
]
