"""Immutable knowledge releases and atomic active-version switching."""

from .service import (
    ActivateReleaseRequest,
    KnowledgeRelease,
    KnowledgeReleaseConflict,
    KnowledgeReleaseError,
    KnowledgeReleaseEvent,
    KnowledgeReleaseGateError,
    KnowledgeReleaseItem,
    KnowledgeReleaseNotFound,
    KnowledgeReleasePreparationError,
    KnowledgeReleaseRepository,
    KnowledgeReleaseState,
    PublishReleaseRequest,
    ReleaseAction,
    ReleaseStatus,
    RetryReleaseRequest,
    RollbackReleaseRequest,
    build_knowledge_release,
    calculate_manifest_sha256,
)

__all__ = [
    "ActivateReleaseRequest",
    "KnowledgeRelease",
    "KnowledgeReleaseConflict",
    "KnowledgeReleaseError",
    "KnowledgeReleaseEvent",
    "KnowledgeReleaseGateError",
    "KnowledgeReleaseItem",
    "KnowledgeReleaseNotFound",
    "KnowledgeReleasePreparationError",
    "KnowledgeReleaseRepository",
    "KnowledgeReleaseState",
    "PublishReleaseRequest",
    "ReleaseAction",
    "ReleaseStatus",
    "RetryReleaseRequest",
    "RollbackReleaseRequest",
    "build_knowledge_release",
    "calculate_manifest_sha256",
]
